### ISSUE TITLE
they comparing my actual good unique clients to this piece of paste 

### ISSUE THREAD

**Issue by Zane2b2t** [AllahLeaksHvH/Storm-Client#3]

**Comment by boy-kisser** [comment]
your client sucks too stfu

**Comment by boy-kisser** [comment]
![image](https://github.com/AllahLeaksHvH/Storm-Client/assets/93730971/36810b7f-5325-48b1-8bc8-bf0069fc3cc7)

**Comment by Zane2b2t** [comment]
> ![image](https://user-images.githubusercontent.com/93730971/243738094-36810b7f-5325-48b1-8bc8-bf0069fc3cc7.png)

thats quantum+ litearly
you dont have grassware-rewrite

**Comment by Zane2b2t** [comment]
> that's from cascade (which pasted it from kami5) so maybe instead of baiting you should be on your knees thanking me for leaking it so you can paste it into your skidware

why would i paste oyvey that has 0 unique modules and garbage code

**Comment by boy-kisser** [comment]
you tell me silly

**Comment by legendaryhvher** [comment]
> > that's from cascade (which pasted it from kami5) so maybe instead of baiting you should be on your knees thanking me for leaking it so you can paste it into your skidware
> 
> why would i paste oyvey that has 0 unique modules and garbage code

cascade has 0 unique modules: grassware rewrite
